[build]
builder = "nixpacks"
buildCommand = "npm install && echo Building bossmanbot!"

[phases]
  [phases.build]
  runtime = "nodejs@16.5.0"

[deploy]
startCommand = "node main.js"
restartPolicyType = "always"
# Remove the healthcheck since the bot is not a web service