[build]
builder = "nixpacks"
buildCommand = "npm install && echo Building bossmanbot!"

[phases]
  [phases.setup]
  nodejs = "16.5.0"

[deploy]
startCommand = "node main.js"
restartPolicyType = "always"